### ISSUE TITLE
Cant use the plugin

### ISSUE THREAD

**Issue by Dysthy** [xam74er1/Text-to-Schematics#1]
I receive this exception
when i try to use /sharpe

[12:39:16] [Thread-34/WARN]: Exception in thread "Thread-34" java.lang.RuntimeException: jakarta.websocket.DeploymentException: Handshake error.
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//fr.xam74er1.text2schem.WebsocketClientEndpoint.<init>(WebsocketClientEndpoint.java:34)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//fr.xam74er1.text2schem.SharpeCommand$1.run(SharpeCommand.java:124)
[12:39:16] [Thread-34/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:39:16] [Thread-34/WARN]: Caused by: jakarta.websocket.DeploymentException: Handshake error.
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:658)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:696)
[12:39:16] [Thread-34/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:39:16] [Thread-34/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:849)
[12:39:16] [Thread-34/WARN]: 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:493)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:355)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//fr.xam74er1.text2schem.WebsocketClientEndpoint.<init>(WebsocketClientEndpoint.java:32)
[12:39:16] [Thread-34/WARN]: 	... 2 more
[12:39:16] [Thread-34/WARN]: Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 403.
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:301)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleHandshake(GrizzlyClientFilter.java:323)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:292)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
[12:39:16] [Thread-34/WARN]: 	at text2schem-1.0-SNAPSHOT.jar//org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
[12:39:16] [Thread-34/WARN]: 	... 1 more

**Comment by xam74er1** [comment]
Hi thank for reporting this issue . 

Did you have run the plugin in local , if it the case did you have open all the port . 
Witch url have you setup ? when you have run the command the command the collab was still running ? 

It look like the issue is a 403 forbiden acces : 

> Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 403. 

You can also use the google colab to just generate the schematics and import as a normal schematics in your world .

**Comment by Dysthy** [comment]
i run the plugin in a dedicated server, wich port need to be open?

**Comment by xam74er1** [comment]
I think you need to see your fire wall rule to allow the plugin to make http request . 
Also be sure to make your Google collab up to date (if is not the case run retart the environement and set the new url with /seturl ) 

it can also be related to your intel firewall rule , you can maybe find more information here : https://github.com/gotify/server/issues/372 

If this solution dont work I can try to help you by discord this weekend .
